node_resources:
  - iron_ore
  - copper_ore
  - limestone
  - coal

resources:
  - iron_ingot
  - copper_ingot
  - steel_ingot
  - iron_plate
  - iron_rod
  - wire
  - cable
  - screw
  - rotor
  - modular_frame
  - reinforced_iron_plate
  - smart_plating
  - steel_beam
  - steel_pipe
  - encased_industrial_beam
  - concrete
  - versatile_framework
  - stator
  - automated_wiring
  - motor
  - oil_node_pure
  - oil_node_normal
  - oil_node_impure
  - crude_oil
  - rubber
  - heavy_oil_residue
  - polymer_resin
  - water
  - plastic

miners:
  miner_mk.1:
      power: 5
      rate: 60
  miner_mk.2:
      power: 12
      rate: 120

machines:
  smelter:
    power: 4
    recipies:
      - {inputs: {copper_ore: 30}, outputs: {copper_ingot: 30}}
      - {inputs: {iron_ore: 30}, outputs: {iron_ingot: 30}}
      
  constructor:
    power: 4
    recipies:
      - {inputs: {iron_ingot: 30}, outputs: {iron_plate: 20}}
      - {inputs: {iron_ingot: 15}, outputs: {iron_rod: 15}}
      - {inputs: {copper_ingot: 15}, outputs: {wire: 30}}
      - {inputs: {wire: 60}, outputs: {cable: 30}}
      - {inputs: {iron_rod: 10}, outputs: {screw: 40}}
      - {inputs: {steel_ingot: 60}, outputs: {steel_beam: 15}}
      - {inputs: {steel_ingot: 30}, outputs: {steel_pipe: 20}}
      - {inputs: {limestone: 45}, outputs: {concrete: 15}}

  assembler:
    power: 15
    recipies:
      - {inputs: {iron_rod: 20, screw: 100}, outputs: {rotor: 4}}
      - {inputs: {iron_plate: 30, screw: 60}, outputs: {reinforced_iron_plate: 5}}
      - {inputs: {reinforced_iron_plate: 2, rotor: 2}, outputs: {smart_plating: 2}}
      - {inputs: {reinforced_iron_plate: 3, iron_rod: 12}, outputs: {modular_frame: 2}}
      - {inputs: {steel_beam: 24, concrete: 30}, outputs: {encased_industrial_beam: 6}}
      - {inputs: {steel_beam: 30, modular_frame: 2.5}, outputs: {versatile_framework: 5}}
      - {inputs: {steel_pipe: 15, wire: 40}, outputs: {stator: 5}}
      - {inputs: {stator: 2.5, cable: 50}, outputs: {automated_wiring: 2.5}}
      - {inputs: {stator: 10, rotor: 10}, outputs: {motor: 5}}

  foundry:
    power: 16
    recipies:
      - {inputs: {iron_ore: 45, coal: 45}, outputs: {steel_ingot: 45}}

  oil_extractor:
    power: 40
    recipies:
      - {inputs: {oil_node_pure: 1}, outputs: {crude_oil: 240}}
      - {inputs: {oil_node_normal: 1}, outputs: {crude_oil: 120}}
      - {inputs: {oil_node_impure: 1}, outputs: {crude_oil: 60}}

  refinery:
    power: 30
    recipies:
      - {inputs: {crude_oil: 30}, outputs: {rubber: 20, heavy_oil_residue: 20}}
      - {inputs: {crude_oil: 30}, outputs: {plastic: 20, heavy_oil_residue: 10}}
      - {inputs: {polymer_resin: 40, water: 40}, outputs: {rubber: 20}}
      - {inputs: {polymer_resin: 60, water: 20}, outputs: {plastic: 20}}

  water_extractor:
    power: 20
    recipies:
      - {inputs: {}, outputs: {water: 120}}
